os: linux

services:
- docker

sudo: required

language: python

env:
  matrix:
      - GCC_VERSION=4.6
      - GCC_VERSION=4.8
      - GCC_VERSION=4.9
      - GCC_VERSION=5.2
      - GCC_VERSION=5.3
      - GCC_VERSION=5.4
      - GCC_VERSION=6.2
      - GCC_VERSION=6.3  

notifications:
  email:
    recipients:
    - estermann.michel@gmail.com
    on_success: change
    on_failure: always

install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - python rebuild_and_upload.py $GCC_VERSION
